<?php
/**
 * @var $this Bubble_AdminTheme_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="box">
    <div style="background:url('http://i.imgur.com/NtYmWIh.png') no-repeat left center;padding-left:55px;min-height:42px;">
        <a href="https://github.com/jreinke/magento-admin-theme" target="_blank" style="float:right;">
            <img src="http://i.imgur.com/QVKwCFx.png" alt="Fork me on GitHub" title="Fork me on GitHub" />
        </a>
        <h4><?php echo $this->helper('bubble_admintheme')->__('Bubble AdminTheme allows you to change the theme of Magento Admin Panel.'); ?></h4>
        <p style="margin-bottom:0;"><?php echo $this->helper('bubble_admintheme')->__('Full overview available'); ?> <a href="<?php echo $this->escapeHtml($this->helper('bubble_admintheme')->__('http://www.bubblecode.net/en/2012/05/02/give-your-magento-admin-panel-a-facelift/')); ?>" target="_blank"><?php echo $this->helper('bubble_admintheme')->__('here'); ?></a>.</p>
    </div>
</div>